name: E2E Tests

on:
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 60
    runs-on: windows-latest  # Changed to Windows

    # Define environment variables (use secrets for sensitive info)
    env:
      url: https://staging.interlynk.io/auth
      email: amaljoseami@gmail.com
      password: LynkRisk@1.0

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Run Playwright tests
      run: npx playwright test
      env:
        url: ${{ env.url }}
        email: ${{ env.email }}
        password: ${{ env.password }}

    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30